// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarouselControls: typeof import('./src/components/swper/CarouselControls.vue')['default']
    ControlBar: typeof import('./src/components/videoPlayer/ControlBar.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Player: typeof import('./src/components/test/player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Swiper: typeof import('./src/components/test/swiper.vue')['default']
    SwiperVideo: typeof import('./src/components/swper/SwiperVideo.vue')['default']
    UserHeader: typeof import('./src/components/my/userHeader/UserHeader.vue')['default']
    VideoAction: typeof import('./src/components/videoComponents/videoAction/VideoAction.vue')['default']
    VideoComments: typeof import('./src/components/videoComponents/videoComments/VideoComments.vue')['default']
    VideoInfo: typeof import('./src/components/videoComponents/videoInfo/VideoInfo.vue')['default']
    VideoPlay: typeof import('./src/components/VideoPlay.vue')['default']
    VideoPlayer: typeof import('./src/components/videoPlayer/index.vue')['default']
    VideoSidebarBtn: typeof import('./src/components/videoComponents/videoSidebarBtn/VideoSidebarBtn.vue')['default']
    VideoSidebarButton: typeof import('./src/components/videoComponents/videoSidebarBtn/VideoSidebarButton.vue')['default']
    ViliPlayer: typeof import('./src/components/videoPlayer/ViliPlayer.vue')['default']
  }
}
